{
 "title": "Rialto+Millau maintenance dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rialto: storage proof overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Rialto_to_Millau_MessageLane_00000000_rialto_storage_proof_overhead",
     "legendFormat": "Actual overhead"
    },
    { "expr": "1024", "legendFormat": "At runtime (hardcoded)" }
   ]
  },
  {
   "title": "Rialto: Millau -> Rialto conversion rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Westend_to_Millau_Sync_kusama_to_base_conversion_rate / Westend_to_Millau_Sync_zaxis_to_base_conversion_rate",
     "legendFormat": "Outside of runtime (actually Z-Axis -> Kusama)"
    },
    {
     "expr": "Rialto_to_Millau_MessageLane_00000000_rialto_millau_to_rialto_conversion_rate",
     "legendFormat": "At runtime"
    }
   ]
  },
  {
   "title": "Millau: storage proof overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Millau_to_Rialto_MessageLane_00000000_millau_storage_proof_overhead",
     "legendFormat": "Actual overhead"
    },
    { "expr": "1024", "legendFormat": "At runtime (hardcoded)" }
   ]
  },
  {
   "title": "Millau: Rialto -> Millau conversion rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Westend_to_Millau_Sync_zaxis_to_base_conversion_rate / Westend_to_Millau_Sync_kusama_to_base_conversion_rate",
     "legendFormat": "Outside of runtime (actually Kusama -> Z-Axis)"
    },
    {
     "expr": "Millau_to_Rialto_MessageLane_00000000_millau_rialto_to_millau_conversion_rate",
     "legendFormat": "At runtime"
    }
   ]
  }
 ]
}