#!/bin/sh

set -e

action="$1"
config_file="/etc/default/zaxis"

if [ "$action" = "configure" ]; then
  # Make user and group
  getent group zaxis >/dev/null 2>&1 || addgroup --system zaxis
  getent passwd zaxis >/dev/null 2>&1 ||
    adduser --system --home /home/zaxis --disabled-password \
    --ingroup zaxis zaxis
  if [ ! -e "$config_file" ]; then
    echo 'ZAXIS_CLI_ARGS=""' > /etc/default/zaxis
  fi
fi
